name: Validação de Código
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar HTMLHint
        run: npm install -g htmlhint
      - name: Validar HTML
        run: htmlhint index.html
