name: Validação de Código
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar HTMLHint
        run: npm install -g htmlhint
      - name: Validar HTML
        run: htmlhint "**/*.html"
      - name: Instalar Stylelint
        run: npm install -g stylelint stylelint-config-standard
      - name: Validar CSS
        run: stylelint "**/*.css"
